# Generated by Django 4.2.5 on 2023-09-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='serial',
            field=models.CharField(auto_created=True, max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='robot',
            unique_together={('model', 'version')},
        ),
    ]
